### ISSUE TITLE
add command does not work

### ISSUE THREAD

**Issue by szalata** [CS2103AUG2017-W09-B1/main#113]
"add n/John Doe g/Male p/98765432 e/johnd@example.com a/John street, block 123, #01-01 m/A0134232H tt/http://modsn.us/AC71u" command is not accepted.
Output:
Invalid command format! 
add: Adds a person to the address book. Parameters: n/NAME g/GENDER m/MATRIC NO. p/PHONE e/EMAIL a/ADDRESS b/BIRTHDAY tt/TIMETABLE_URL [t/TAG]...
Example: add n/John Doe g/Male m/A0162533K p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 b/21051994 tt/http://modsn.us/AbCdE t/friends t/owesMoney

**Comment by marvinchin** [comment]
I think you're missing the birthday field

**Comment by szalata** [comment]
Then it is an issue with the user guide, as I read:
![image](https://user-images.githubusercontent.com/17835212/32363120-9cf4891a-c0a8-11e7-9b0f-bb69ca8fa89f.png)

**Comment by chernghann** [comment]
Same issue is faced for me. Do update the user guide to ensure that the fields are supposed to be compulsory or optional

**Comment by szalata** [comment]
Other examples not following the requirements:
![image](https://user-images.githubusercontent.com/17835212/32363284-89c8b734-c0a9-11e7-9139-9be6588170cb.png)

**Comment by chernghann** [comment]
Adding the person with the shortlink  http://modsn.us/AC71u provided in the user guide works, however it doesnt work with my personal nusmods link. Good job with the nusmods implementation

**Comment by zacharytang** [comment]
@chernghann interesting, do you mind sharing your personal nusmods link?
