### ISSUE TITLE
Tag size too small

### ISSUE THREAD

**Issue by WangJieee** [CS2103AUG2017-W09-B1/main#116]
Additional suggestion: It would be better to display tags with same name with same background colour for easier identification :)

**Comment by nbriannl** [comment]
Clarification needed. What do you mean by tags with same name?

**Comment by WangJieee** [comment]
<img width="366" alt="screen shot 2017-11-04 at 12 01 35 pm" src="https://user-images.githubusercontent.com/28586077/32402010-781da538-c0d8-11e7-83dc-6640d33aa62d.png">
For example, the 'friends' tag for Alex and Bernice has different background colour. Perhaps you can make them the same colour.
Also, I notice that in the tag panel, tag that no longer belongs to anyone (e.g 'owesMoney' tag after I use edit to remove it from the person) is changed to a red background, which to me seems more obvious than the rest. So perhaps you can consider switching the colour, making removed tags appear grey instead? Just a suggestion.

**Comment by nbriannl** [comment]
Thank you for the suggestion.
Fixed with #152 

![image](https://user-images.githubusercontent.com/27397021/32532242-f546734c-c483-11e7-8a52-6613e5386c36.png)

![image](https://user-images.githubusercontent.com/27397021/32532248-00b7b178-c484-11e7-8a12-5fbb4664f1a6.png)
