### ISSUE TITLE
Birthday in Contact Card

### ISSUE THREAD

**Issue by marvinchin** [CS2103AUG2017-W09-B1/main#119]
Birthday is currently displayed as DDMMYYYY in the contact card, which can be difficult to read. Is there any intention to parse it as a more readable string? e.g. 10 Feb 1990 instead of 10021990

**Comment by April0616** [comment]
oh, thanks for your suggestion

**Comment by zacharytang** [comment]
Issue resolved with #136, as field is no longer displayed in person card
