### ISSUE TITLE
Does not display the correct format when user enters wrong format

### ISSUE THREAD

**Issue by siri99** [CS2103AUG2017-W09-B1/main#120]
It would be better if AddressBook could display the correct way of using a command in the command box when the user enters a commad in the wrong format. 

For eg, when I just type "Delete Alex" in the command line, it does not show me the correct way to input parameters to the command. For a new user, this will be confusing as he/she will not know the right way to use the command. Would be easier if correct format such as "Delete [INDEX]" was displayed.

![image](https://user-images.githubusercontent.com/29172477/32363464-79eaa7d6-c0aa-11e7-8893-529f58117189.png)

**Comment by April0616** [comment]
![image](https://user-images.githubusercontent.com/19221372/32401407-8d2ff0be-c148-11e7-950c-62b8fa88fbc8.png)
oh, I think this is a jar file problem. It will actually display the correct format. :)
Thanks!
