### ISSUE TITLE
Delete tag function

### ISSUE THREAD

**Issue by chernghann** [CS2103AUG2017-W09-B1/main#121]
Suggestion: to delete specific tag from person only, for example you have many neighbours but only 1 neighbour shifted house, delete t/neighbour will remove all neighbours.

**Comment by April0616** [comment]
oh, the 'delete t/neighbour' command is used to delete all the neighbour tags, if you want to clear the neighbour tag of one specific person, you should use "edit 1 t/" to clear it. 
Maybe it's not clear in UserGuide, sorry.
