### ISSUE TITLE
Display area on the right has no scroll bar to view full info

### ISSUE THREAD

**Issue by WangJieee** [CS2103AUG2017-W09-B1/main#125]
<img width="933" alt="screen shot 2017-11-03 at 3 40 08 pm" src="https://user-images.githubusercontent.com/28586077/32363785-3f2b5504-c02e-11e7-9dfc-5ad468cd6aa3.png">
When adding a long remark, the full remark can not be viewed in the person tag as well as on the display area on the right

**Comment by April0616** [comment]
oh, thanks for pointing out! We'll try to improve this
