### ISSUE TITLE
Bug: nothing works when Help window is opened

### ISSUE THREAD

**Issue by Kennard123661** [CS2103AUG2017-W09-B1/main#189]
Hey guys, 

Brian's friend here, we are doing acceptance testing for each other. What I found is that your application ceases to process any events etc. when the help window is open.

I think its a bug carried over from AB4. A fix for it can be found in this issue:
https://github.com/se-edu/addressbook-level4/issues/727

My team's application does not have this issue. I think we fixed it in this PR:
https://github.com/CS2103AUG2017-T16-B1/main/issues/164

**Comment by zacharytang** [comment]
Thanks for pointing it out!

**Comment by nbriannl** [comment]
Fixes #187

**Comment by nbriannl** [comment]
Closes #187

**Comment by nbriannl** [comment]
Fix #187
