### ISSUE TITLE
Edit Command: Display Message (Person - Birthday)

### ISSUE THREAD

**Issue by April0616** [CS2103AUG2017-W09-B1/main#194]
Wrong display message when entering non-exist date.
Edit Birthday: Wrong display message when entering non-exist '02292017'

![image](https://user-images.githubusercontent.com/19221372/32685703-6aad61aa-c6d1-11e7-95e6-3fdee6b8c0ed.png)

![image](https://user-images.githubusercontent.com/19221372/32685717-b1b9eb68-c6d1-11e7-9f1c-982725175fa7.png)

**Comment by nbriannl** [comment]
I will do for edit tag! Separated it into another issue #226
