### ISSUE TITLE
If one tag is so long, the format will be messy.

### ISSUE THREAD

**Issue by April0616** [CS2103AUG2017-W09-B1/main#196]
Both the Tag panel and the infopanel will be affected if the tag is so long, maybe the user cannot see other tags as there is no space.

If the user want to add a long tag, the display message will be 'The content is so long, would you like to add a remark instead? It would be : remark INDEX r/[The tag entered] '

![image](https://user-images.githubusercontent.com/19221372/32685934-df8a9628-c6d6-11e7-8689-1b08584b8ef8.png)

**Comment by CindyTsai1** [comment]
#229  solved
