### ISSUE TITLE
FindCommand : The app doesn't response

### ISSUE THREAD

**Issue by April0616** [CS2103AUG2017-W09-B1/main#197]
When I try to find the persons who have 'hahah' in the name and 'sci' in the tag, the app does not give any response!

![image](https://user-images.githubusercontent.com/19221372/32685984-79f23446-c6d7-11e7-89a4-d025f3e7ab07.png)

**Comment by nbriannl** [comment]
@CindyTsai1 will be doing Find Command

**Comment by CindyTsai1** [comment]
works on my version. the bug should be fixed in the most recent pr. just have to wait for Zach to fix the test then merge
