### ISSUE TITLE
Delete tag: case-sensitive

### ISSUE THREAD

**Issue by April0616** [CS2103AUG2017-W09-B1/main#200]
![image](https://user-images.githubusercontent.com/19221372/32686252-5b246598-c6dc-11e7-99ae-5f8a8e04d288.png)

Could we make it case-insensitive?

**Comment by nbriannl** [comment]
Delete Tag is case sensitive because Tags are Case Sensitive. Example: goodFriends and GOODfriends are unique tags. Delete t/goodFriends will delete both tags.

**Comment by nbriannl** [comment]
Unless... I don't allow to add a new tag that is exactly the same word but different case

**Comment by zacharytang** [comment]
I think that it should be case sensitive, considering we differentiate tags by case as well.
